description:
  This section describes all of the services that may be present on the AP.
  Each service is then referenced via its name inside an interface, ssid, ...
type: object
properties:
  lldp:
    $ref: "https://ucentral.io/schema/v1/service/lldp/"
  ssh:
    $ref: "https://ucentral.io/schema/v1/service/ssh/"
  ntp:
    $ref: "https://ucentral.io/schema/v1/service/ntp/"
  log:
    $ref: "https://ucentral.io/schema/v1/service/log/"
  igmp:
    $ref: "https://ucentral.io/schema/v1/service/igmp/"
  ieee8021x:
    $ref: "https://ucentral.io/schema/v1/service/ieee8021x/"
  radius-proxy:
    $ref: "https://ucentral.io/schema/v1/service/radius-proxy/"
  online-check:
    $ref: "https://ucentral.io/schema/v1/service/online-check/"
  data-plane:
    $ref: "https://ucentral.io/schema/v1/service/data-plane/"
  quality-of-service:
    $ref: "https://ucentral.io/schema/v1/service/quality-of-service/"
  airtime-fairness:
    $ref: "https://ucentral.io/schema/v1/service/airtime-fairness/"
  captive:
    $ref: 'https://ucentral.io/schema/v1/service/captive/'
  gps:
    $ref: 'https://ucentral.io/schema/v1/service/gps/'
  dhcp-relay:
    $ref: 'https://ucentral.io/schema/v1/service/dhcp-relay/'
  admin-ui:
    $ref: 'https://ucentral.io/schema/v1/service/admin-ui/'
  rrm:
    $ref: 'https://ucentral.io/schema/v1/service/rrm/'
  fingerprint:
    $ref: 'https://ucentral.io/schema/v1/service/fingerprint/'
  snmpd:
    $ref: 'https://ucentral.io/schema/v1/service/snmpd/'
  dhcp-inject:
    $ref: 'https://ucentral.io/schema/v1/service/dhcp-inject/'
